version: 2

builds:
  - id: ozzie
    main: ./cmd/ozzie
    binary: ozzie
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

dockers:
  - image_templates: ["ghcr.io/dohr-michael/ozzie:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates: ["--platform=linux/amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    extra_files: [scripts/detect-tools.sh]

  - image_templates: ["ghcr.io/dohr-michael/ozzie:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates: ["--platform=linux/arm64"]
    goarch: arm64
    dockerfile: Dockerfile
    extra_files: [scripts/detect-tools.sh]

docker_manifests:
  - name_template: "ghcr.io/dohr-michael/ozzie:{{ .Version }}"
    image_templates:
      - "ghcr.io/dohr-michael/ozzie:{{ .Version }}-amd64"
      - "ghcr.io/dohr-michael/ozzie:{{ .Version }}-arm64"
  - name_template: "ghcr.io/dohr-michael/ozzie:latest"
    image_templates:
      - "ghcr.io/dohr-michael/ozzie:{{ .Version }}-amd64"
      - "ghcr.io/dohr-michael/ozzie:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:"]
