package wizard

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// ConfigData holds the data for rendering the JSONC config template.
type ConfigData struct {
	ProviderName string   // e.g. "claude", "gpt"
	Driver       string   // e.g. "anthropic", "openai"
	Model        string
	BaseURL      string   // optional (ollama)
	AuthEnvVar   string   // e.g. "ANTHROPIC_API_KEY"
	Capabilities []string // e.g. ["tool_use", "coding"]
	Tags         []string // e.g. ["self-hosted", "primary"]
	GatewayHost  string
	GatewayPort  int
}

// driverProviderNames maps driver names to friendly provider names.
var driverProviderNames = map[string]string{
	"anthropic": "claude",
	"openai":    "gpt",
	"gemini":    "gemini",
	"mistral":   "mistral",
	"ollama":    "local",
}

// driverEnvVars maps driver names to their expected env var for the API key.
var driverEnvVars = map[string]string{
	"anthropic": "ANTHROPIC_API_KEY",
	"openai":    "OPENAI_API_KEY",
	"gemini":    "GOOGLE_API_KEY",
	"mistral":   "MISTRAL_API_KEY",
}

// BuildConfigData creates a ConfigData from wizard answers.
func BuildConfigData(answers Answers) ConfigData {
	driver := answers.String("driver", "anthropic")
	providerName := driverProviderNames[driver]
	if providerName == "" {
		providerName = driver
	}

	return ConfigData{
		ProviderName: providerName,
		Driver:       driver,
		Model:        answers.String("model", "claude-sonnet-4-20250514"),
		BaseURL:      answers.String("base_url", ""),
		AuthEnvVar:   driverEnvVars[driver],
		Capabilities: answers.Strings("capabilities", nil),
		Tags:         answers.Strings("tags", nil),
		GatewayHost:  answers.String("gateway_host", "127.0.0.1"),
		GatewayPort:  answers.Int("gateway_port", 18420),
	}
}

const configTemplate = `{
    // Ozzie Configuration — generated by ozzie wake

    "gateway": {
        "host": "{{ .GatewayHost }}",
        "port": {{ .GatewayPort }}
    },

    "models": {
        "default": "{{ .ProviderName }}",
        "providers": {
            "{{ .ProviderName }}": {
                "driver": "{{ .Driver }}",
                "model": "{{ .Model }}",
{{- if .BaseURL }}
                "base_url": "{{ .BaseURL }}",
{{- end }}
{{- if .AuthEnvVar }}
                "auth": {
                    "api_key": "${{"{{"}} .Env.{{ .AuthEnvVar }} {{"}}"}}"
                },
{{- end }}
{{- if .Capabilities }}
                "capabilities": {{ jsonArray .Capabilities }},
{{- end }}
{{- if .Tags }}
                "tags": {{ jsonArray .Tags }},
{{- end }}
                "max_tokens": 4096
            }
        }
    },

    "events": {
        "buffer_size": 1024
    },

    "agent": {
        "system_prompt": ""
    }
}
`

// jsonArray formats a string slice as a JSON array (e.g. ["a", "b"]).
func jsonArray(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = `"` + s + `"`
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// RenderConfig renders the JSONC config from the given data.
func RenderConfig(data ConfigData) (string, error) {
	funcMap := template.FuncMap{"jsonArray": jsonArray}
	tmpl, err := template.New("config").Funcs(funcMap).Parse(configTemplate)
	if err != nil {
		return "", fmt.Errorf("parse config template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute config template: %w", err)
	}
	return buf.String(), nil
}
